port: 5000
db_url: "postgres://postgres:NeEHo3rGQsiND8w@postgres:5432/kanban?sslmode=disable"
jwt_secret: "roFQaRHN2g/o2qHE8G4cAKa36aU6Yd61UqUsK69NHsD4dQaJqK49jr7j3mpOXkfpvQo="
client_url: "http://localhost:5173"
